### ISSUE TITLE
1.5 View Timer

### ISSUE THREAD

**Issue by merforga** [Voltron-BIS/TOYL#20]

**Comment by merforga** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sprint 1 Development](https://trello.com/c/OwctE7RY/477-sprint-1-development)

**Comment by iamaleaf** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sprint 2 Development](https://trello.com/c/vhEOT9ax/478-sprint-2-development)

**Comment by iamaleaf** [comment]
Closed as broken down into more specific issues. See:
#56 #57 #58
