### ISSUE TITLE
5.1 Statistic visualisation

### ISSUE THREAD

**Issue by merforga** [Voltron-BIS/TOYL#29]

**Comment by s3632442** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sprint 2 Development](https://trello.com/c/vhEOT9ax/478-sprint-2-development)

**Comment by s3632442** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sprint 1 Development](https://trello.com/c/OwctE7RY/477-sprint-1-development)
